PROGRAMS_spu    := spunoptest
LIBRARY_embed   := spunoptest.a

INCLUDE = -I$(CELL_SDK_ROOT)/usr/spu/include
LDFLAGS = -L$(CELL_SDK_ROOT)/sysroot/usr/spu/lib/ -lmisc

include $(CELL_SDK_ROOT)/make.footer
